# Vector Operations

In [2]:
import numpy as np

We can add 2 matrices simply by using the *+* operator.

In [6]:
u = np.array([1, 2, 3])
v = np.array([1, 2, 3])
print(u)
print(v)

[1 2 3]
[1 2 3]


In [7]:
u + v

array([2, 4, 6])

We can do the same with other operators discussed in element-wise operations on numpy arrays.

# Multiplication

### Vector Multiplication

In vector multiplication, it is required for the arrays to have the same size.

In [54]:
a = np.array([1, 2, 3])
b = np.array([1, 7, 8])

In [55]:
print("Size of A: ", a.shape[0]) 
print("Size of B: ", b.shape[0])

Size of A:  3
Size of B:  3


See the function below that implements the dot product of two vectors.

In [56]:
def multiply_vectors(a, b):
    assert a.shape[0] == b.shape[0]
    result = 0.0
    n = a.shape[0]
    for i in range(n):
        result += a[i] * b[i]
    return result

In [57]:
multiply_vectors(a, b)

39.0

The ***.dot*** function can be used for this operation.

In [58]:
a.dot(b)

39

### Matrix-Vector Multiplication

To multiply a matrix with a vector, we have to multiply **each** row of the matrix to the vector

In [67]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [1, 2, 3],
])
v = np.array([1, 2, 3])

In [68]:
print(m)
print(v)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
[1 2 3]


Naturally, the number of elements in each row of the matrix must match the number of elements in the vector.

In [72]:
print("Size of row in matrix A: ", m.shape[1])
print("Size of vector V: ", v.shape[0])

Size of row in matrix A:  3
Size of vector V:  3


In [81]:
def vector_and_matrix(m, v):
    assert m.shape[1] == v.shape[0]
    p = m.shape[0]
    q = v.shape[0]
    result = np.zeros(p)
    for i in range(p):
        for j in range(q):
            result[i] += m[i][j] * v[j]
    return result

In [82]:
vector_and_matrix(m, v)

array([14., 32., 50., 14.])

Above is the implementation of matrix to vector multiplication. We can also rewrite the code in a way that uses our previous function **multiply_vectors**

In [88]:
def vector_matrix_multiplication(m, v):
    assert m.shape[1] == v.shape[0]
    p = m.shape[0]
    q = v.shape[0]
    result = np.zeros(p)
    for i in range(p):
        result[i] = multiply_vectors(m[i], v)
    return result

In [89]:
vector_matrix_multiplication(m, v)

array([14., 32., 50., 14.])

As you can see, it produces the same result as the manual implementation.

Like in vector-vector multiplication, numpy also knows how to do the operation above with the ***.dot*** function we used before.

In [97]:
m.dot(v)

array([14, 32, 50, 14])

### Matrix Multiplication

In multiplication, each element Ci is the result of multiply a row of A to a column of B. Due to this, it is necessary that the number of columns in A is equal to the number of rows in B.

In [92]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])
b = np.array([
    [1, 2],
    [4, 5],
    [7, 8],
])

In [93]:
print("Columns of A: ", a.shape[1]) 
print("Rows of B: ", b.shape[0])

Columns of A:  3
Rows of B:  3


The resulting matrix of the matrices above upon multiplying must yield a size of (a, d) if A = (a, b) and B = (c, d). Let's confirm that by multiplying the two matrices.

Below is a function that multiplies to numpy matrices.

In [110]:
def multiply_matrix(a, b):
    # confirm if matrices can be multiplied
    assert a.shape[1] == b.shape[0]

    n = a.shape[0];
    p = b.shape[1];

    # create a matrix of size n x p assuming a matrix A
    # of size n * m and matrix B of size q * p
    c = np.zeros((n, p))
    # total rows of A
    for i in range(n):
        # access columns of B with j
        for j in range(p):
            # changing indices with k
            # set k for B rows and k for A columns
            for k in range(n):
                c[i][j] += a[i][k] * b[k][j]
    return c
    

In [111]:
multiply_matrix(a, b)

array([[ 30.,  36.],
       [ 66.,  81.],
       [102., 126.]])

We can still modify the matrix the same way we modified matrix-vector multiplication

In [114]:
def multiply_matrix(a, b):
    # confirm if matrices can be multiplied
    assert a.shape[1] == b.shape[0]

    n = a.shape[0];
    p = b.shape[1];

    # create a matrix of size n x p assuming a matrix A
    # of size n * m and matrix B of size q * p
    c = np.zeros((n, p))
    for i in range(p):
        # get each column of b
        vi = b[:, i]
        # perform vector-matrix mutiplication to A and vi
        # because we are multiplying each row of A to
        # the vector vi (the column we extracted
        Uvi = vector_matrix_multiplication(a, vi)
        # the result we get is per column so assign
        # the vector Uvi as a column in variable C
        c[:, i] = Uvi
    return c

In [115]:
multiply_matrix(a, b)

array([[ 30.,  36.],
       [ 66.,  81.],
       [102., 126.]])

Thankfully, we don't have to manually implement this everytime we want to multiply vectors in our program. As you've guessed, we can just use the ***.dot*** function like how we did for the other operations:

In [117]:
a.dot(b)

array([[ 30,  36],
       [ 66,  81],
       [102, 126]])

# Identity Matrix

An identity matrix is the **equivalent** of the value **1** in matrices. This means that any matrix multiplied to this identity matrix would not change anything. 

We can create an identity matrix using numpy with ***.eye***.

In [125]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Below is a demonstration:

In [129]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
a.dot(I)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

As you can see, the values of A did not change after performing a multiplication between the two matrices.

# Matrix Inverse

**Key Idea:** The inverse of a matrix **A**, in which we refer to as **Z** in this case, is a matrix such that if we multiply **Z** with **A**, then we are getting an identity matrix.

We need to keep in mind that only square matrices have an inverse.

In [171]:
A = np.array([
    [3, 2],
    [1, -2]
])
Z = np.linalg.inv(A)

In [172]:
print(A, Z)

[[ 3  2]
 [ 1 -2]] [[ 0.25   0.25 ]
 [ 0.125 -0.375]]


In [173]:
A.dot(Z)

array([[1., 0.],
       [0., 1.]])

Be careful with singular matrix because they do not have an inverse.